# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='poins',
            new_name='points',
        ),
    ]
